# 修复版！2026 GitHub百分百成功部署yml
name: Deploy Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库全部文件
        uses: actions/checkout@v4
      - name: 打包部署静态网页
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          allow_empty_commit: false
